name: Sedstart Cloud Run

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 612
          test_id: 1234
          profile_id: 1017
          browser: chrome
          headless: false
